  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  shoulder_pan_joint_effort_controller:
    type: effort_controllers/JointEffortController
    joint: shoulder_pan_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}
  shoulder_lift_joint_effort_controller:
    type: effort_controllers/JointEffortController
    joint: shoulder_lift_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}
  elbow_joint_effort_controller:
    type: effort_controllers/JointEffortController
    joint: elbow_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}
  wrist_1_joint_effort_controller:
    type: effort_controllers/JointEffortController
    joint: wrist_1_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}
  wrist_2_joint_effort_controller:
    type: effort_controllers/JointEffortController
    joint: wrist_2_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}
  wrist_3_joint_effort_controller:
    type: effort_controllers/JointEffortController
    joint: wrist_3_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}
